server:
  port: 8081

spring:
  application:
    name: config-server

cloud:
  config:
    git:
      uri: https://github.com/josefina-oller/configuration-server.git
      searchPaths: config-data
      username: ${GIT_USER}
      password: ${GIT_PASSWORD}